# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_water_mainwd(object):
    def setupUi(self, water_mainwd):
        if not water_mainwd.objectName():
            water_mainwd.setObjectName(u"water_mainwd")
        water_mainwd.resize(1031, 832)
        water_mainwd.setContextMenuPolicy(Qt.DefaultContextMenu)
        water_mainwd.setToolButtonStyle(Qt.ToolButtonIconOnly)
        self.centralwidget = QWidget(water_mainwd)
        self.centralwidget.setObjectName(u"centralwidget")
        self.result_lbl = QTextBrowser(self.centralwidget)
        self.result_lbl.setObjectName(u"result_lbl")
        self.result_lbl.setGeometry(QRect(20, 590, 901, 181))
        self.exec_btn = QPushButton(self.centralwidget)
        self.exec_btn.setObjectName(u"exec_btn")
        self.exec_btn.setGeometry(QRect(930, 660, 81, 61))
        self.clear_output_btn = QPushButton(self.centralwidget)
        self.clear_output_btn.setObjectName(u"clear_output_btn")
        self.clear_output_btn.setGeometry(QRect(930, 590, 51, 31))
        self.open_when_fin_btn = QCheckBox(self.centralwidget)
        self.open_when_fin_btn.setObjectName(u"open_when_fin_btn")
        self.open_when_fin_btn.setGeometry(QRect(990, 630, 21, 21))
        self.open_when_fin_btn.setChecked(True)
        self.label_36 = QLabel(self.centralwidget)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(930, 620, 61, 41))
        self.sel_input_lbl = QLineEdit(self.centralwidget)
        self.sel_input_lbl.setObjectName(u"sel_input_lbl")
        self.sel_input_lbl.setGeometry(QRect(210, 10, 531, 21))
        self.sel_input_btn = QPushButton(self.centralwidget)
        self.sel_input_btn.setObjectName(u"sel_input_btn")
        self.sel_input_btn.setGeometry(QRect(170, 10, 21, 28))
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 10, 161, 21))
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 60, 161, 21))
        self.sel_output_btn = QPushButton(self.centralwidget)
        self.sel_output_btn.setObjectName(u"sel_output_btn")
        self.sel_output_btn.setGeometry(QRect(170, 60, 21, 28))
        self.sel_output_lbl = QLineEdit(self.centralwidget)
        self.sel_output_lbl.setObjectName(u"sel_output_lbl")
        self.sel_output_lbl.setGeometry(QRect(210, 60, 531, 21))
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 90, 981, 441))
        self.frame.setStyleSheet(u"border: 2px;\n"
"background-color: rgb(185, 209, 205);")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.tabWidget = QTabWidget(self.frame)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 10, 961, 421))
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.label_21 = QLabel(self.tab_1)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 30, 161, 21))
        self.date_creatfile_st = QDateTimeEdit(self.tab_1)
        self.date_creatfile_st.setObjectName(u"date_creatfile_st")
        self.date_creatfile_st.setGeometry(QRect(180, 30, 194, 22))
        self.date_creatfile_st.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.date_creatfile_st.setDateTime(QDateTime(QDate(2021, 1, 1), QTime(0, 0, 0)))
        self.label_22 = QLabel(self.tab_1)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(400, 30, 41, 21))
        self.date_creatfile_ed = QDateTimeEdit(self.tab_1)
        self.date_creatfile_ed.setObjectName(u"date_creatfile_ed")
        self.date_creatfile_ed.setGeometry(QRect(440, 30, 194, 22))
        self.date_creatfile_ed.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.date_creatfile_ed.setDateTime(QDateTime(QDate(2021, 12, 1), QTime(0, 0, 0)))
        self.label_23 = QLabel(self.tab_1)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(660, 30, 121, 21))
        self.label_24 = QLabel(self.tab_1)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 80, 261, 21))
        self.date_modfile_st = QDoubleSpinBox(self.tab_1)
        self.date_modfile_st.setObjectName(u"date_modfile_st")
        self.date_modfile_st.setGeometry(QRect(280, 80, 66, 22))
        self.date_modfile_st.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.date_modfile_st.setValue(1.000000000000000)
        self.label_26 = QLabel(self.tab_1)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(400, 80, 41, 21))
        self.date_modfile_ed = QDoubleSpinBox(self.tab_1)
        self.date_modfile_ed.setObjectName(u"date_modfile_ed")
        self.date_modfile_ed.setGeometry(QRect(440, 80, 66, 22))
        self.date_modfile_ed.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.date_modfile_ed.setValue(48.000000000000000)
        self.label_27 = QLabel(self.tab_1)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(540, 80, 241, 21))
        self.label_28 = QLabel(self.tab_1)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 130, 261, 21))
        self.date_visfile_ed = QDoubleSpinBox(self.tab_1)
        self.date_visfile_ed.setObjectName(u"date_visfile_ed")
        self.date_visfile_ed.setGeometry(QRect(440, 130, 66, 22))
        self.date_visfile_ed.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.date_visfile_ed.setValue(48.000000000000000)
        self.date_visfile_st = QDoubleSpinBox(self.tab_1)
        self.date_visfile_st.setObjectName(u"date_visfile_st")
        self.date_visfile_st.setGeometry(QRect(280, 130, 66, 22))
        self.date_visfile_st.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.date_visfile_st.setValue(1.000000000000000)
        self.label_29 = QLabel(self.tab_1)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(540, 130, 241, 21))
        self.label_30 = QLabel(self.tab_1)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(400, 130, 41, 21))
        self.modattr_filter = QTextEdit(self.tab_1)
        self.modattr_filter.setObjectName(u"modattr_filter")
        self.modattr_filter.setGeometry(QRect(10, 220, 151, 91))
        self.modattr_filter.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_31 = QLabel(self.tab_1)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 180, 161, 21))
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.fr_replace_1 = QFrame(self.tab_2)
        self.fr_replace_1.setObjectName(u"fr_replace_1")
        self.fr_replace_1.setGeometry(QRect(0, 10, 401, 41))
        self.fr_replace_1.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_1.setFrameShadow(QFrame.Raised)
        self.replace_input_lbl_1 = QLineEdit(self.fr_replace_1)
        self.replace_input_lbl_1.setObjectName(u"replace_input_lbl_1")
        self.replace_input_lbl_1.setGeometry(QRect(40, 10, 141, 21))
        self.replace_input_lbl_1.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_32 = QLabel(self.fr_replace_1)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 10, 31, 21))
        self.label_33 = QLabel(self.fr_replace_1)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(190, 10, 51, 21))
        self.replace_output_lbl_1 = QLineEdit(self.fr_replace_1)
        self.replace_output_lbl_1.setObjectName(u"replace_output_lbl_1")
        self.replace_output_lbl_1.setGeometry(QRect(240, 10, 151, 21))
        self.replace_output_lbl_1.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_57 = QLabel(self.tab_2)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(710, 290, 241, 101))
        self.label_57.setScaledContents(False)
        self.label_57.setWordWrap(True)
        self.label_58 = QLabel(self.tab_2)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(10, 260, 161, 21))
        self.replacefile_filter = QTextEdit(self.tab_2)
        self.replacefile_filter.setObjectName(u"replacefile_filter")
        self.replacefile_filter.setGeometry(QRect(10, 290, 151, 91))
        self.replacefile_filter.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fr_replace_2 = QFrame(self.tab_2)
        self.fr_replace_2.setObjectName(u"fr_replace_2")
        self.fr_replace_2.setGeometry(QRect(440, 10, 401, 41))
        self.fr_replace_2.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_2.setFrameShadow(QFrame.Raised)
        self.replace_input_lbl_2 = QLineEdit(self.fr_replace_2)
        self.replace_input_lbl_2.setObjectName(u"replace_input_lbl_2")
        self.replace_input_lbl_2.setGeometry(QRect(40, 10, 141, 21))
        self.replace_input_lbl_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_34 = QLabel(self.fr_replace_2)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 10, 31, 21))
        self.label_35 = QLabel(self.fr_replace_2)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(190, 10, 51, 21))
        self.replace_output_lbl_2 = QLineEdit(self.fr_replace_2)
        self.replace_output_lbl_2.setObjectName(u"replace_output_lbl_2")
        self.replace_output_lbl_2.setGeometry(QRect(240, 10, 151, 21))
        self.replace_output_lbl_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fr_replace_3 = QFrame(self.tab_2)
        self.fr_replace_3.setObjectName(u"fr_replace_3")
        self.fr_replace_3.setGeometry(QRect(0, 50, 401, 41))
        self.fr_replace_3.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_3.setFrameShadow(QFrame.Raised)
        self.replace_input_lbl_3 = QLineEdit(self.fr_replace_3)
        self.replace_input_lbl_3.setObjectName(u"replace_input_lbl_3")
        self.replace_input_lbl_3.setGeometry(QRect(40, 10, 141, 21))
        self.replace_input_lbl_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_37 = QLabel(self.fr_replace_3)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(10, 10, 31, 21))
        self.label_38 = QLabel(self.fr_replace_3)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(190, 10, 51, 21))
        self.replace_output_lbl_3 = QLineEdit(self.fr_replace_3)
        self.replace_output_lbl_3.setObjectName(u"replace_output_lbl_3")
        self.replace_output_lbl_3.setGeometry(QRect(240, 10, 151, 21))
        self.replace_output_lbl_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fr_replace_4 = QFrame(self.tab_2)
        self.fr_replace_4.setObjectName(u"fr_replace_4")
        self.fr_replace_4.setGeometry(QRect(440, 50, 401, 41))
        self.fr_replace_4.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_4.setFrameShadow(QFrame.Raised)
        self.replace_input_lbl_4 = QLineEdit(self.fr_replace_4)
        self.replace_input_lbl_4.setObjectName(u"replace_input_lbl_4")
        self.replace_input_lbl_4.setGeometry(QRect(40, 10, 141, 21))
        self.replace_input_lbl_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_39 = QLabel(self.fr_replace_4)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(10, 10, 31, 21))
        self.label_40 = QLabel(self.fr_replace_4)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(190, 10, 51, 21))
        self.replace_output_lbl_4 = QLineEdit(self.fr_replace_4)
        self.replace_output_lbl_4.setObjectName(u"replace_output_lbl_4")
        self.replace_output_lbl_4.setGeometry(QRect(240, 10, 151, 21))
        self.replace_output_lbl_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fr_replace_5 = QFrame(self.tab_2)
        self.fr_replace_5.setObjectName(u"fr_replace_5")
        self.fr_replace_5.setGeometry(QRect(0, 90, 401, 41))
        self.fr_replace_5.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_5.setFrameShadow(QFrame.Raised)
        self.replace_input_lbl_5 = QLineEdit(self.fr_replace_5)
        self.replace_input_lbl_5.setObjectName(u"replace_input_lbl_5")
        self.replace_input_lbl_5.setGeometry(QRect(40, 10, 141, 21))
        self.replace_input_lbl_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_41 = QLabel(self.fr_replace_5)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 10, 31, 21))
        self.label_42 = QLabel(self.fr_replace_5)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(190, 10, 51, 21))
        self.replace_output_lbl_5 = QLineEdit(self.fr_replace_5)
        self.replace_output_lbl_5.setObjectName(u"replace_output_lbl_5")
        self.replace_output_lbl_5.setGeometry(QRect(240, 10, 151, 21))
        self.replace_output_lbl_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fr_replace_6 = QFrame(self.tab_2)
        self.fr_replace_6.setObjectName(u"fr_replace_6")
        self.fr_replace_6.setGeometry(QRect(440, 90, 401, 41))
        self.fr_replace_6.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_6.setFrameShadow(QFrame.Raised)
        self.replace_input_lbl_6 = QLineEdit(self.fr_replace_6)
        self.replace_input_lbl_6.setObjectName(u"replace_input_lbl_6")
        self.replace_input_lbl_6.setGeometry(QRect(40, 10, 141, 21))
        self.replace_input_lbl_6.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_43 = QLabel(self.fr_replace_6)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(10, 10, 31, 21))
        self.label_44 = QLabel(self.fr_replace_6)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(190, 10, 51, 21))
        self.replace_output_lbl_6 = QLineEdit(self.fr_replace_6)
        self.replace_output_lbl_6.setObjectName(u"replace_output_lbl_6")
        self.replace_output_lbl_6.setGeometry(QRect(240, 10, 151, 21))
        self.replace_output_lbl_6.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fr_replace_7 = QFrame(self.tab_2)
        self.fr_replace_7.setObjectName(u"fr_replace_7")
        self.fr_replace_7.setGeometry(QRect(0, 130, 401, 41))
        self.fr_replace_7.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_7.setFrameShadow(QFrame.Raised)
        self.replace_input_lbl_7 = QLineEdit(self.fr_replace_7)
        self.replace_input_lbl_7.setObjectName(u"replace_input_lbl_7")
        self.replace_input_lbl_7.setGeometry(QRect(40, 10, 141, 21))
        self.replace_input_lbl_7.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_45 = QLabel(self.fr_replace_7)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(10, 10, 31, 21))
        self.label_46 = QLabel(self.fr_replace_7)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(190, 10, 51, 21))
        self.replace_output_lbl_7 = QLineEdit(self.fr_replace_7)
        self.replace_output_lbl_7.setObjectName(u"replace_output_lbl_7")
        self.replace_output_lbl_7.setGeometry(QRect(240, 10, 151, 21))
        self.replace_output_lbl_7.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fr_replace_8 = QFrame(self.tab_2)
        self.fr_replace_8.setObjectName(u"fr_replace_8")
        self.fr_replace_8.setGeometry(QRect(440, 130, 401, 41))
        self.fr_replace_8.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_8.setFrameShadow(QFrame.Raised)
        self.replace_input_lbl_8 = QLineEdit(self.fr_replace_8)
        self.replace_input_lbl_8.setObjectName(u"replace_input_lbl_8")
        self.replace_input_lbl_8.setGeometry(QRect(40, 10, 141, 21))
        self.replace_input_lbl_8.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_47 = QLabel(self.fr_replace_8)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(10, 10, 31, 21))
        self.label_48 = QLabel(self.fr_replace_8)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(190, 10, 51, 21))
        self.replace_output_lbl_8 = QLineEdit(self.fr_replace_8)
        self.replace_output_lbl_8.setObjectName(u"replace_output_lbl_8")
        self.replace_output_lbl_8.setGeometry(QRect(240, 10, 151, 21))
        self.replace_output_lbl_8.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fr_replace_9 = QFrame(self.tab_2)
        self.fr_replace_9.setObjectName(u"fr_replace_9")
        self.fr_replace_9.setGeometry(QRect(0, 170, 401, 41))
        self.fr_replace_9.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_9.setFrameShadow(QFrame.Raised)
        self.replace_input_lbl_9 = QLineEdit(self.fr_replace_9)
        self.replace_input_lbl_9.setObjectName(u"replace_input_lbl_9")
        self.replace_input_lbl_9.setGeometry(QRect(40, 10, 141, 21))
        self.replace_input_lbl_9.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_49 = QLabel(self.fr_replace_9)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(10, 10, 31, 21))
        self.label_50 = QLabel(self.fr_replace_9)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(190, 10, 51, 21))
        self.replace_output_lbl_9 = QLineEdit(self.fr_replace_9)
        self.replace_output_lbl_9.setObjectName(u"replace_output_lbl_9")
        self.replace_output_lbl_9.setGeometry(QRect(240, 10, 151, 21))
        self.replace_output_lbl_9.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fr_replace_10 = QFrame(self.tab_2)
        self.fr_replace_10.setObjectName(u"fr_replace_10")
        self.fr_replace_10.setGeometry(QRect(440, 170, 401, 41))
        self.fr_replace_10.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_10.setFrameShadow(QFrame.Raised)
        self.replace_input_lbl_10 = QLineEdit(self.fr_replace_10)
        self.replace_input_lbl_10.setObjectName(u"replace_input_lbl_10")
        self.replace_input_lbl_10.setGeometry(QRect(40, 10, 141, 21))
        self.replace_input_lbl_10.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_51 = QLabel(self.fr_replace_10)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(10, 10, 31, 21))
        self.label_52 = QLabel(self.fr_replace_10)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(190, 10, 51, 21))
        self.replace_output_lbl_10 = QLineEdit(self.fr_replace_10)
        self.replace_output_lbl_10.setObjectName(u"replace_output_lbl_10")
        self.replace_output_lbl_10.setGeometry(QRect(240, 10, 151, 21))
        self.replace_output_lbl_10.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fr_replace_11 = QFrame(self.tab_2)
        self.fr_replace_11.setObjectName(u"fr_replace_11")
        self.fr_replace_11.setGeometry(QRect(0, 210, 401, 41))
        self.fr_replace_11.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_11.setFrameShadow(QFrame.Raised)
        self.replace_input_lbl_11 = QLineEdit(self.fr_replace_11)
        self.replace_input_lbl_11.setObjectName(u"replace_input_lbl_11")
        self.replace_input_lbl_11.setGeometry(QRect(40, 10, 141, 21))
        self.replace_input_lbl_11.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_53 = QLabel(self.fr_replace_11)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(10, 10, 31, 21))
        self.label_54 = QLabel(self.fr_replace_11)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(190, 10, 51, 21))
        self.replace_output_lbl_11 = QLineEdit(self.fr_replace_11)
        self.replace_output_lbl_11.setObjectName(u"replace_output_lbl_11")
        self.replace_output_lbl_11.setGeometry(QRect(240, 10, 151, 21))
        self.replace_output_lbl_11.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fr_replace_12 = QFrame(self.tab_2)
        self.fr_replace_12.setObjectName(u"fr_replace_12")
        self.fr_replace_12.setGeometry(QRect(440, 210, 401, 41))
        self.fr_replace_12.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_12.setFrameShadow(QFrame.Raised)
        self.replace_input_lbl_12 = QLineEdit(self.fr_replace_12)
        self.replace_input_lbl_12.setObjectName(u"replace_input_lbl_12")
        self.replace_input_lbl_12.setGeometry(QRect(40, 10, 141, 21))
        self.replace_input_lbl_12.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_55 = QLabel(self.fr_replace_12)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(10, 10, 31, 21))
        self.label_56 = QLabel(self.fr_replace_12)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(190, 10, 51, 21))
        self.replace_output_lbl_12 = QLineEdit(self.fr_replace_12)
        self.replace_output_lbl_12.setObjectName(u"replace_output_lbl_12")
        self.replace_output_lbl_12.setGeometry(QRect(240, 10, 151, 21))
        self.replace_output_lbl_12.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.rootshow_filter = QTextEdit(self.tab_3)
        self.rootshow_filter.setObjectName(u"rootshow_filter")
        self.rootshow_filter.setGeometry(QRect(240, 150, 151, 91))
        self.rootshow_filter.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_20 = QLabel(self.tab_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(240, 110, 211, 21))
        self.radioButton_toprint = QRadioButton(self.tab_3)
        self.radioButton_toprint.setObjectName(u"radioButton_toprint")
        self.radioButton_toprint.setGeometry(QRect(470, 120, 115, 19))
        self.radioButton_toprint.setChecked(False)
        self.radioButton_toword = QRadioButton(self.tab_3)
        self.radioButton_toword.setObjectName(u"radioButton_toword")
        self.radioButton_toword.setGeometry(QRect(470, 150, 161, 19))
        self.radioButton_toword.setChecked(True)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.fr_replace_13 = QFrame(self.tab_4)
        self.fr_replace_13.setObjectName(u"fr_replace_13")
        self.fr_replace_13.setGeometry(QRect(10, 10, 451, 31))
        self.fr_replace_13.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_13.setFrameShadow(QFrame.Raised)
        self.label_59 = QLabel(self.fr_replace_13)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(10, 5, 31, 21))
        self.label_60 = QLabel(self.fr_replace_13)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(180, 5, 51, 21))
        self.label_61 = QLabel(self.fr_replace_13)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(90, 5, 31, 21))
        self.input_year_1 = QSpinBox(self.fr_replace_13)
        self.input_year_1.setObjectName(u"input_year_1")
        self.input_year_1.setGeometry(QRect(40, 5, 51, 22))
        self.input_year_1.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_year_1.setMinimum(1900)
        self.input_year_1.setMaximum(3000)
        self.input_year_1.setValue(2000)
        self.input_month_1 = QSpinBox(self.fr_replace_13)
        self.input_month_1.setObjectName(u"input_month_1")
        self.input_month_1.setGeometry(QRect(110, 5, 51, 22))
        self.input_month_1.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_month_1.setMinimum(1)
        self.input_month_1.setMaximum(12)
        self.input_month_1.setValue(1)
        self.label_62 = QLabel(self.fr_replace_13)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(160, 5, 21, 21))
        self.label_63 = QLabel(self.fr_replace_13)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(280, 5, 31, 21))
        self.label_64 = QLabel(self.fr_replace_13)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(350, 5, 31, 21))
        self.output_month_1 = QSpinBox(self.fr_replace_13)
        self.output_month_1.setObjectName(u"output_month_1")
        self.output_month_1.setGeometry(QRect(300, 5, 51, 22))
        self.output_month_1.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_month_1.setMinimum(1)
        self.output_month_1.setMaximum(12)
        self.output_month_1.setValue(1)
        self.output_year_1 = QSpinBox(self.fr_replace_13)
        self.output_year_1.setObjectName(u"output_year_1")
        self.output_year_1.setGeometry(QRect(230, 5, 51, 22))
        self.output_year_1.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_year_1.setMinimum(1900)
        self.output_year_1.setMaximum(3000)
        self.output_year_1.setValue(2021)
        self.date_enable_1 = QCheckBox(self.fr_replace_13)
        self.date_enable_1.setObjectName(u"date_enable_1")
        self.date_enable_1.setGeometry(QRect(380, 5, 61, 19))
        self.date_enable_1.setChecked(True)
        self.year_input_to_all = QPushButton(self.tab_4)
        self.year_input_to_all.setObjectName(u"year_input_to_all")
        self.year_input_to_all.setGeometry(QRect(550, 10, 231, 51))
        self.year_input_to_all.setStyleSheet(u"background-color: rgb(0, 170, 127);")
        self.month_asc_input = QPushButton(self.tab_4)
        self.month_asc_input.setObjectName(u"month_asc_input")
        self.month_asc_input.setGeometry(QRect(550, 90, 231, 51))
        self.month_asc_input.setStyleSheet(u"background-color: rgb(0, 170, 127);")
        self.fr_replace_14 = QFrame(self.tab_4)
        self.fr_replace_14.setObjectName(u"fr_replace_14")
        self.fr_replace_14.setGeometry(QRect(10, 40, 451, 31))
        self.fr_replace_14.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_14.setFrameShadow(QFrame.Raised)
        self.label_65 = QLabel(self.fr_replace_14)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(10, 5, 31, 21))
        self.label_66 = QLabel(self.fr_replace_14)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(180, 5, 51, 21))
        self.label_67 = QLabel(self.fr_replace_14)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(90, 5, 31, 21))
        self.input_year_2 = QSpinBox(self.fr_replace_14)
        self.input_year_2.setObjectName(u"input_year_2")
        self.input_year_2.setGeometry(QRect(40, 5, 51, 22))
        self.input_year_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_year_2.setMinimum(1900)
        self.input_year_2.setMaximum(3000)
        self.input_year_2.setValue(2000)
        self.input_month_2 = QSpinBox(self.fr_replace_14)
        self.input_month_2.setObjectName(u"input_month_2")
        self.input_month_2.setGeometry(QRect(110, 5, 51, 22))
        self.input_month_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_month_2.setMinimum(1)
        self.input_month_2.setMaximum(12)
        self.input_month_2.setValue(1)
        self.label_68 = QLabel(self.fr_replace_14)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(160, 5, 21, 21))
        self.label_69 = QLabel(self.fr_replace_14)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(280, 5, 31, 21))
        self.label_70 = QLabel(self.fr_replace_14)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(350, 5, 31, 21))
        self.output_month_2 = QSpinBox(self.fr_replace_14)
        self.output_month_2.setObjectName(u"output_month_2")
        self.output_month_2.setGeometry(QRect(300, 5, 51, 22))
        self.output_month_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_month_2.setMinimum(1)
        self.output_month_2.setMaximum(12)
        self.output_month_2.setValue(1)
        self.output_year_2 = QSpinBox(self.fr_replace_14)
        self.output_year_2.setObjectName(u"output_year_2")
        self.output_year_2.setGeometry(QRect(230, 5, 51, 22))
        self.output_year_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_year_2.setMinimum(1900)
        self.output_year_2.setMaximum(3000)
        self.output_year_2.setValue(2021)
        self.date_enable_2 = QCheckBox(self.fr_replace_14)
        self.date_enable_2.setObjectName(u"date_enable_2")
        self.date_enable_2.setGeometry(QRect(380, 5, 61, 19))
        self.date_enable_2.setChecked(True)
        self.fr_replace_15 = QFrame(self.tab_4)
        self.fr_replace_15.setObjectName(u"fr_replace_15")
        self.fr_replace_15.setGeometry(QRect(10, 70, 451, 31))
        self.fr_replace_15.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_15.setFrameShadow(QFrame.Raised)
        self.label_71 = QLabel(self.fr_replace_15)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(10, 5, 31, 21))
        self.label_72 = QLabel(self.fr_replace_15)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(180, 5, 51, 21))
        self.label_73 = QLabel(self.fr_replace_15)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(90, 5, 31, 21))
        self.input_year_3 = QSpinBox(self.fr_replace_15)
        self.input_year_3.setObjectName(u"input_year_3")
        self.input_year_3.setGeometry(QRect(40, 5, 51, 22))
        self.input_year_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_year_3.setMinimum(1900)
        self.input_year_3.setMaximum(3000)
        self.input_year_3.setValue(2000)
        self.input_month_3 = QSpinBox(self.fr_replace_15)
        self.input_month_3.setObjectName(u"input_month_3")
        self.input_month_3.setGeometry(QRect(110, 5, 51, 22))
        self.input_month_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_month_3.setMinimum(1)
        self.input_month_3.setMaximum(12)
        self.input_month_3.setValue(1)
        self.label_74 = QLabel(self.fr_replace_15)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(160, 5, 21, 21))
        self.label_75 = QLabel(self.fr_replace_15)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(280, 5, 31, 21))
        self.label_76 = QLabel(self.fr_replace_15)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(350, 5, 31, 21))
        self.output_month_3 = QSpinBox(self.fr_replace_15)
        self.output_month_3.setObjectName(u"output_month_3")
        self.output_month_3.setGeometry(QRect(300, 5, 51, 22))
        self.output_month_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_month_3.setMinimum(1)
        self.output_month_3.setMaximum(12)
        self.output_month_3.setValue(1)
        self.output_year_3 = QSpinBox(self.fr_replace_15)
        self.output_year_3.setObjectName(u"output_year_3")
        self.output_year_3.setGeometry(QRect(230, 5, 51, 22))
        self.output_year_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_year_3.setMinimum(1900)
        self.output_year_3.setMaximum(3000)
        self.output_year_3.setValue(2021)
        self.date_enable_3 = QCheckBox(self.fr_replace_15)
        self.date_enable_3.setObjectName(u"date_enable_3")
        self.date_enable_3.setGeometry(QRect(380, 5, 61, 19))
        self.date_enable_3.setChecked(True)
        self.fr_replace_16 = QFrame(self.tab_4)
        self.fr_replace_16.setObjectName(u"fr_replace_16")
        self.fr_replace_16.setGeometry(QRect(10, 100, 451, 31))
        self.fr_replace_16.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_16.setFrameShadow(QFrame.Raised)
        self.label_77 = QLabel(self.fr_replace_16)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(10, 5, 31, 21))
        self.label_78 = QLabel(self.fr_replace_16)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setGeometry(QRect(180, 5, 51, 21))
        self.label_79 = QLabel(self.fr_replace_16)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setGeometry(QRect(90, 5, 31, 21))
        self.input_year_4 = QSpinBox(self.fr_replace_16)
        self.input_year_4.setObjectName(u"input_year_4")
        self.input_year_4.setGeometry(QRect(40, 5, 51, 22))
        self.input_year_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_year_4.setMinimum(1900)
        self.input_year_4.setMaximum(3000)
        self.input_year_4.setValue(2000)
        self.input_month_4 = QSpinBox(self.fr_replace_16)
        self.input_month_4.setObjectName(u"input_month_4")
        self.input_month_4.setGeometry(QRect(110, 5, 51, 22))
        self.input_month_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_month_4.setMinimum(1)
        self.input_month_4.setMaximum(12)
        self.input_month_4.setValue(1)
        self.label_80 = QLabel(self.fr_replace_16)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setGeometry(QRect(160, 5, 21, 21))
        self.label_81 = QLabel(self.fr_replace_16)
        self.label_81.setObjectName(u"label_81")
        self.label_81.setGeometry(QRect(280, 5, 31, 21))
        self.label_82 = QLabel(self.fr_replace_16)
        self.label_82.setObjectName(u"label_82")
        self.label_82.setGeometry(QRect(350, 5, 31, 21))
        self.output_month_4 = QSpinBox(self.fr_replace_16)
        self.output_month_4.setObjectName(u"output_month_4")
        self.output_month_4.setGeometry(QRect(300, 5, 51, 22))
        self.output_month_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_month_4.setMinimum(1)
        self.output_month_4.setMaximum(12)
        self.output_month_4.setValue(1)
        self.output_year_4 = QSpinBox(self.fr_replace_16)
        self.output_year_4.setObjectName(u"output_year_4")
        self.output_year_4.setGeometry(QRect(230, 5, 51, 22))
        self.output_year_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_year_4.setMinimum(1900)
        self.output_year_4.setMaximum(3000)
        self.output_year_4.setValue(2021)
        self.date_enable_4 = QCheckBox(self.fr_replace_16)
        self.date_enable_4.setObjectName(u"date_enable_4")
        self.date_enable_4.setGeometry(QRect(380, 5, 61, 19))
        self.date_enable_4.setChecked(True)
        self.fr_replace_17 = QFrame(self.tab_4)
        self.fr_replace_17.setObjectName(u"fr_replace_17")
        self.fr_replace_17.setGeometry(QRect(10, 130, 451, 31))
        self.fr_replace_17.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_17.setFrameShadow(QFrame.Raised)
        self.label_83 = QLabel(self.fr_replace_17)
        self.label_83.setObjectName(u"label_83")
        self.label_83.setGeometry(QRect(10, 5, 31, 21))
        self.label_84 = QLabel(self.fr_replace_17)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setGeometry(QRect(180, 5, 51, 21))
        self.label_85 = QLabel(self.fr_replace_17)
        self.label_85.setObjectName(u"label_85")
        self.label_85.setGeometry(QRect(90, 5, 31, 21))
        self.input_year_5 = QSpinBox(self.fr_replace_17)
        self.input_year_5.setObjectName(u"input_year_5")
        self.input_year_5.setGeometry(QRect(40, 5, 51, 22))
        self.input_year_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_year_5.setMinimum(1900)
        self.input_year_5.setMaximum(3000)
        self.input_year_5.setValue(2000)
        self.input_month_5 = QSpinBox(self.fr_replace_17)
        self.input_month_5.setObjectName(u"input_month_5")
        self.input_month_5.setGeometry(QRect(110, 5, 51, 22))
        self.input_month_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_month_5.setMinimum(1)
        self.input_month_5.setMaximum(12)
        self.input_month_5.setValue(1)
        self.label_86 = QLabel(self.fr_replace_17)
        self.label_86.setObjectName(u"label_86")
        self.label_86.setGeometry(QRect(160, 5, 21, 21))
        self.label_87 = QLabel(self.fr_replace_17)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setGeometry(QRect(280, 5, 31, 21))
        self.label_88 = QLabel(self.fr_replace_17)
        self.label_88.setObjectName(u"label_88")
        self.label_88.setGeometry(QRect(350, 5, 31, 21))
        self.output_month_5 = QSpinBox(self.fr_replace_17)
        self.output_month_5.setObjectName(u"output_month_5")
        self.output_month_5.setGeometry(QRect(300, 5, 51, 22))
        self.output_month_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_month_5.setMinimum(1)
        self.output_month_5.setMaximum(12)
        self.output_month_5.setValue(1)
        self.output_year_5 = QSpinBox(self.fr_replace_17)
        self.output_year_5.setObjectName(u"output_year_5")
        self.output_year_5.setGeometry(QRect(230, 5, 51, 22))
        self.output_year_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_year_5.setMinimum(1900)
        self.output_year_5.setMaximum(3000)
        self.output_year_5.setValue(2021)
        self.date_enable_5 = QCheckBox(self.fr_replace_17)
        self.date_enable_5.setObjectName(u"date_enable_5")
        self.date_enable_5.setGeometry(QRect(380, 5, 61, 19))
        self.date_enable_5.setChecked(True)
        self.fr_replace_18 = QFrame(self.tab_4)
        self.fr_replace_18.setObjectName(u"fr_replace_18")
        self.fr_replace_18.setGeometry(QRect(10, 160, 451, 31))
        self.fr_replace_18.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_18.setFrameShadow(QFrame.Raised)
        self.label_89 = QLabel(self.fr_replace_18)
        self.label_89.setObjectName(u"label_89")
        self.label_89.setGeometry(QRect(10, 5, 31, 21))
        self.label_90 = QLabel(self.fr_replace_18)
        self.label_90.setObjectName(u"label_90")
        self.label_90.setGeometry(QRect(180, 5, 51, 21))
        self.label_91 = QLabel(self.fr_replace_18)
        self.label_91.setObjectName(u"label_91")
        self.label_91.setGeometry(QRect(90, 5, 31, 21))
        self.input_year_6 = QSpinBox(self.fr_replace_18)
        self.input_year_6.setObjectName(u"input_year_6")
        self.input_year_6.setGeometry(QRect(40, 5, 51, 22))
        self.input_year_6.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_year_6.setMinimum(1900)
        self.input_year_6.setMaximum(3000)
        self.input_year_6.setValue(2000)
        self.input_month_6 = QSpinBox(self.fr_replace_18)
        self.input_month_6.setObjectName(u"input_month_6")
        self.input_month_6.setGeometry(QRect(110, 5, 51, 22))
        self.input_month_6.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_month_6.setMinimum(1)
        self.input_month_6.setMaximum(12)
        self.input_month_6.setValue(1)
        self.label_92 = QLabel(self.fr_replace_18)
        self.label_92.setObjectName(u"label_92")
        self.label_92.setGeometry(QRect(160, 5, 21, 21))
        self.label_93 = QLabel(self.fr_replace_18)
        self.label_93.setObjectName(u"label_93")
        self.label_93.setGeometry(QRect(280, 5, 31, 21))
        self.label_94 = QLabel(self.fr_replace_18)
        self.label_94.setObjectName(u"label_94")
        self.label_94.setGeometry(QRect(350, 5, 31, 21))
        self.output_month_6 = QSpinBox(self.fr_replace_18)
        self.output_month_6.setObjectName(u"output_month_6")
        self.output_month_6.setGeometry(QRect(300, 5, 51, 22))
        self.output_month_6.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_month_6.setMinimum(1)
        self.output_month_6.setMaximum(12)
        self.output_month_6.setValue(1)
        self.output_year_6 = QSpinBox(self.fr_replace_18)
        self.output_year_6.setObjectName(u"output_year_6")
        self.output_year_6.setGeometry(QRect(230, 5, 51, 22))
        self.output_year_6.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_year_6.setMinimum(1900)
        self.output_year_6.setMaximum(3000)
        self.output_year_6.setValue(2021)
        self.date_enable_6 = QCheckBox(self.fr_replace_18)
        self.date_enable_6.setObjectName(u"date_enable_6")
        self.date_enable_6.setGeometry(QRect(380, 5, 61, 19))
        self.date_enable_6.setChecked(True)
        self.fr_replace_19 = QFrame(self.tab_4)
        self.fr_replace_19.setObjectName(u"fr_replace_19")
        self.fr_replace_19.setGeometry(QRect(10, 190, 451, 31))
        self.fr_replace_19.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_19.setFrameShadow(QFrame.Raised)
        self.label_95 = QLabel(self.fr_replace_19)
        self.label_95.setObjectName(u"label_95")
        self.label_95.setGeometry(QRect(10, 5, 31, 21))
        self.label_96 = QLabel(self.fr_replace_19)
        self.label_96.setObjectName(u"label_96")
        self.label_96.setGeometry(QRect(180, 5, 51, 21))
        self.label_97 = QLabel(self.fr_replace_19)
        self.label_97.setObjectName(u"label_97")
        self.label_97.setGeometry(QRect(90, 5, 31, 21))
        self.input_year_7 = QSpinBox(self.fr_replace_19)
        self.input_year_7.setObjectName(u"input_year_7")
        self.input_year_7.setGeometry(QRect(40, 5, 51, 22))
        self.input_year_7.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_year_7.setMinimum(1900)
        self.input_year_7.setMaximum(3000)
        self.input_year_7.setValue(2000)
        self.input_month_7 = QSpinBox(self.fr_replace_19)
        self.input_month_7.setObjectName(u"input_month_7")
        self.input_month_7.setGeometry(QRect(110, 5, 51, 22))
        self.input_month_7.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_month_7.setMinimum(1)
        self.input_month_7.setMaximum(12)
        self.input_month_7.setValue(1)
        self.label_98 = QLabel(self.fr_replace_19)
        self.label_98.setObjectName(u"label_98")
        self.label_98.setGeometry(QRect(160, 5, 21, 21))
        self.label_99 = QLabel(self.fr_replace_19)
        self.label_99.setObjectName(u"label_99")
        self.label_99.setGeometry(QRect(280, 5, 31, 21))
        self.label_100 = QLabel(self.fr_replace_19)
        self.label_100.setObjectName(u"label_100")
        self.label_100.setGeometry(QRect(350, 5, 31, 21))
        self.output_month_7 = QSpinBox(self.fr_replace_19)
        self.output_month_7.setObjectName(u"output_month_7")
        self.output_month_7.setGeometry(QRect(300, 5, 51, 22))
        self.output_month_7.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_month_7.setMinimum(1)
        self.output_month_7.setMaximum(12)
        self.output_month_7.setValue(1)
        self.output_year_7 = QSpinBox(self.fr_replace_19)
        self.output_year_7.setObjectName(u"output_year_7")
        self.output_year_7.setGeometry(QRect(230, 5, 51, 22))
        self.output_year_7.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_year_7.setMinimum(1900)
        self.output_year_7.setMaximum(3000)
        self.output_year_7.setValue(2021)
        self.date_enable_7 = QCheckBox(self.fr_replace_19)
        self.date_enable_7.setObjectName(u"date_enable_7")
        self.date_enable_7.setGeometry(QRect(380, 5, 61, 19))
        self.date_enable_7.setChecked(True)
        self.fr_replace_20 = QFrame(self.tab_4)
        self.fr_replace_20.setObjectName(u"fr_replace_20")
        self.fr_replace_20.setGeometry(QRect(10, 220, 451, 31))
        self.fr_replace_20.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_20.setFrameShadow(QFrame.Raised)
        self.label_101 = QLabel(self.fr_replace_20)
        self.label_101.setObjectName(u"label_101")
        self.label_101.setGeometry(QRect(10, 5, 31, 21))
        self.label_102 = QLabel(self.fr_replace_20)
        self.label_102.setObjectName(u"label_102")
        self.label_102.setGeometry(QRect(180, 5, 51, 21))
        self.label_103 = QLabel(self.fr_replace_20)
        self.label_103.setObjectName(u"label_103")
        self.label_103.setGeometry(QRect(90, 5, 31, 21))
        self.input_year_8 = QSpinBox(self.fr_replace_20)
        self.input_year_8.setObjectName(u"input_year_8")
        self.input_year_8.setGeometry(QRect(40, 5, 51, 22))
        self.input_year_8.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_year_8.setMinimum(1900)
        self.input_year_8.setMaximum(3000)
        self.input_year_8.setValue(2000)
        self.input_month_8 = QSpinBox(self.fr_replace_20)
        self.input_month_8.setObjectName(u"input_month_8")
        self.input_month_8.setGeometry(QRect(110, 5, 51, 22))
        self.input_month_8.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_month_8.setMinimum(1)
        self.input_month_8.setMaximum(12)
        self.input_month_8.setValue(1)
        self.label_104 = QLabel(self.fr_replace_20)
        self.label_104.setObjectName(u"label_104")
        self.label_104.setGeometry(QRect(160, 5, 21, 21))
        self.label_105 = QLabel(self.fr_replace_20)
        self.label_105.setObjectName(u"label_105")
        self.label_105.setGeometry(QRect(280, 5, 31, 21))
        self.label_106 = QLabel(self.fr_replace_20)
        self.label_106.setObjectName(u"label_106")
        self.label_106.setGeometry(QRect(350, 5, 31, 21))
        self.output_month_8 = QSpinBox(self.fr_replace_20)
        self.output_month_8.setObjectName(u"output_month_8")
        self.output_month_8.setGeometry(QRect(300, 5, 51, 22))
        self.output_month_8.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_month_8.setMinimum(1)
        self.output_month_8.setMaximum(12)
        self.output_month_8.setValue(1)
        self.output_year_8 = QSpinBox(self.fr_replace_20)
        self.output_year_8.setObjectName(u"output_year_8")
        self.output_year_8.setGeometry(QRect(230, 5, 51, 22))
        self.output_year_8.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_year_8.setMinimum(1900)
        self.output_year_8.setMaximum(3000)
        self.output_year_8.setValue(2021)
        self.date_enable_8 = QCheckBox(self.fr_replace_20)
        self.date_enable_8.setObjectName(u"date_enable_8")
        self.date_enable_8.setGeometry(QRect(380, 5, 61, 19))
        self.date_enable_8.setChecked(True)
        self.fr_replace_21 = QFrame(self.tab_4)
        self.fr_replace_21.setObjectName(u"fr_replace_21")
        self.fr_replace_21.setGeometry(QRect(10, 250, 451, 31))
        self.fr_replace_21.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_21.setFrameShadow(QFrame.Raised)
        self.label_107 = QLabel(self.fr_replace_21)
        self.label_107.setObjectName(u"label_107")
        self.label_107.setGeometry(QRect(10, 5, 31, 21))
        self.label_108 = QLabel(self.fr_replace_21)
        self.label_108.setObjectName(u"label_108")
        self.label_108.setGeometry(QRect(180, 5, 51, 21))
        self.label_109 = QLabel(self.fr_replace_21)
        self.label_109.setObjectName(u"label_109")
        self.label_109.setGeometry(QRect(90, 5, 31, 21))
        self.input_year_9 = QSpinBox(self.fr_replace_21)
        self.input_year_9.setObjectName(u"input_year_9")
        self.input_year_9.setGeometry(QRect(40, 5, 51, 22))
        self.input_year_9.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_year_9.setMinimum(1900)
        self.input_year_9.setMaximum(3000)
        self.input_year_9.setValue(2000)
        self.input_month_9 = QSpinBox(self.fr_replace_21)
        self.input_month_9.setObjectName(u"input_month_9")
        self.input_month_9.setGeometry(QRect(110, 5, 51, 22))
        self.input_month_9.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_month_9.setMinimum(1)
        self.input_month_9.setMaximum(12)
        self.input_month_9.setValue(1)
        self.label_110 = QLabel(self.fr_replace_21)
        self.label_110.setObjectName(u"label_110")
        self.label_110.setGeometry(QRect(160, 5, 21, 21))
        self.label_111 = QLabel(self.fr_replace_21)
        self.label_111.setObjectName(u"label_111")
        self.label_111.setGeometry(QRect(280, 5, 31, 21))
        self.label_112 = QLabel(self.fr_replace_21)
        self.label_112.setObjectName(u"label_112")
        self.label_112.setGeometry(QRect(350, 5, 31, 21))
        self.output_month_9 = QSpinBox(self.fr_replace_21)
        self.output_month_9.setObjectName(u"output_month_9")
        self.output_month_9.setGeometry(QRect(300, 5, 51, 22))
        self.output_month_9.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_month_9.setMinimum(1)
        self.output_month_9.setMaximum(12)
        self.output_month_9.setValue(1)
        self.output_year_9 = QSpinBox(self.fr_replace_21)
        self.output_year_9.setObjectName(u"output_year_9")
        self.output_year_9.setGeometry(QRect(230, 5, 51, 22))
        self.output_year_9.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_year_9.setMinimum(1900)
        self.output_year_9.setMaximum(3000)
        self.output_year_9.setValue(2021)
        self.date_enable_9 = QCheckBox(self.fr_replace_21)
        self.date_enable_9.setObjectName(u"date_enable_9")
        self.date_enable_9.setGeometry(QRect(380, 5, 61, 19))
        self.date_enable_9.setChecked(True)
        self.fr_replace_22 = QFrame(self.tab_4)
        self.fr_replace_22.setObjectName(u"fr_replace_22")
        self.fr_replace_22.setGeometry(QRect(10, 280, 451, 31))
        self.fr_replace_22.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_22.setFrameShadow(QFrame.Raised)
        self.label_113 = QLabel(self.fr_replace_22)
        self.label_113.setObjectName(u"label_113")
        self.label_113.setGeometry(QRect(10, 5, 31, 21))
        self.label_114 = QLabel(self.fr_replace_22)
        self.label_114.setObjectName(u"label_114")
        self.label_114.setGeometry(QRect(180, 5, 51, 21))
        self.label_115 = QLabel(self.fr_replace_22)
        self.label_115.setObjectName(u"label_115")
        self.label_115.setGeometry(QRect(90, 5, 31, 21))
        self.input_year_10 = QSpinBox(self.fr_replace_22)
        self.input_year_10.setObjectName(u"input_year_10")
        self.input_year_10.setGeometry(QRect(40, 5, 51, 22))
        self.input_year_10.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_year_10.setMinimum(1900)
        self.input_year_10.setMaximum(3000)
        self.input_year_10.setValue(2000)
        self.input_month_10 = QSpinBox(self.fr_replace_22)
        self.input_month_10.setObjectName(u"input_month_10")
        self.input_month_10.setGeometry(QRect(110, 5, 51, 22))
        self.input_month_10.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_month_10.setMinimum(1)
        self.input_month_10.setMaximum(12)
        self.input_month_10.setValue(1)
        self.label_116 = QLabel(self.fr_replace_22)
        self.label_116.setObjectName(u"label_116")
        self.label_116.setGeometry(QRect(160, 5, 21, 21))
        self.label_117 = QLabel(self.fr_replace_22)
        self.label_117.setObjectName(u"label_117")
        self.label_117.setGeometry(QRect(280, 5, 31, 21))
        self.label_118 = QLabel(self.fr_replace_22)
        self.label_118.setObjectName(u"label_118")
        self.label_118.setGeometry(QRect(350, 5, 31, 21))
        self.output_month_10 = QSpinBox(self.fr_replace_22)
        self.output_month_10.setObjectName(u"output_month_10")
        self.output_month_10.setGeometry(QRect(300, 5, 51, 22))
        self.output_month_10.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_month_10.setMinimum(1)
        self.output_month_10.setMaximum(12)
        self.output_month_10.setValue(1)
        self.output_year_10 = QSpinBox(self.fr_replace_22)
        self.output_year_10.setObjectName(u"output_year_10")
        self.output_year_10.setGeometry(QRect(230, 5, 51, 22))
        self.output_year_10.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_year_10.setMinimum(1900)
        self.output_year_10.setMaximum(3000)
        self.output_year_10.setValue(2021)
        self.date_enable_10 = QCheckBox(self.fr_replace_22)
        self.date_enable_10.setObjectName(u"date_enable_10")
        self.date_enable_10.setGeometry(QRect(380, 5, 61, 19))
        self.date_enable_10.setChecked(True)
        self.fr_replace_23 = QFrame(self.tab_4)
        self.fr_replace_23.setObjectName(u"fr_replace_23")
        self.fr_replace_23.setGeometry(QRect(10, 310, 451, 31))
        self.fr_replace_23.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_23.setFrameShadow(QFrame.Raised)
        self.label_119 = QLabel(self.fr_replace_23)
        self.label_119.setObjectName(u"label_119")
        self.label_119.setGeometry(QRect(10, 5, 31, 21))
        self.label_120 = QLabel(self.fr_replace_23)
        self.label_120.setObjectName(u"label_120")
        self.label_120.setGeometry(QRect(180, 5, 51, 21))
        self.label_121 = QLabel(self.fr_replace_23)
        self.label_121.setObjectName(u"label_121")
        self.label_121.setGeometry(QRect(90, 5, 31, 21))
        self.input_year_11 = QSpinBox(self.fr_replace_23)
        self.input_year_11.setObjectName(u"input_year_11")
        self.input_year_11.setGeometry(QRect(40, 5, 51, 22))
        self.input_year_11.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_year_11.setMinimum(1900)
        self.input_year_11.setMaximum(3000)
        self.input_year_11.setValue(2000)
        self.input_month_11 = QSpinBox(self.fr_replace_23)
        self.input_month_11.setObjectName(u"input_month_11")
        self.input_month_11.setGeometry(QRect(110, 5, 51, 22))
        self.input_month_11.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_month_11.setMinimum(1)
        self.input_month_11.setMaximum(12)
        self.input_month_11.setValue(1)
        self.label_122 = QLabel(self.fr_replace_23)
        self.label_122.setObjectName(u"label_122")
        self.label_122.setGeometry(QRect(160, 5, 21, 21))
        self.label_123 = QLabel(self.fr_replace_23)
        self.label_123.setObjectName(u"label_123")
        self.label_123.setGeometry(QRect(280, 5, 31, 21))
        self.label_124 = QLabel(self.fr_replace_23)
        self.label_124.setObjectName(u"label_124")
        self.label_124.setGeometry(QRect(350, 5, 31, 21))
        self.output_month_11 = QSpinBox(self.fr_replace_23)
        self.output_month_11.setObjectName(u"output_month_11")
        self.output_month_11.setGeometry(QRect(300, 5, 51, 22))
        self.output_month_11.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_month_11.setMinimum(1)
        self.output_month_11.setMaximum(12)
        self.output_month_11.setValue(1)
        self.output_year_11 = QSpinBox(self.fr_replace_23)
        self.output_year_11.setObjectName(u"output_year_11")
        self.output_year_11.setGeometry(QRect(230, 5, 51, 22))
        self.output_year_11.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_year_11.setMinimum(1900)
        self.output_year_11.setMaximum(3000)
        self.output_year_11.setValue(2021)
        self.date_enable_11 = QCheckBox(self.fr_replace_23)
        self.date_enable_11.setObjectName(u"date_enable_11")
        self.date_enable_11.setGeometry(QRect(380, 5, 61, 19))
        self.date_enable_11.setChecked(True)
        self.fr_replace_24 = QFrame(self.tab_4)
        self.fr_replace_24.setObjectName(u"fr_replace_24")
        self.fr_replace_24.setGeometry(QRect(10, 340, 451, 31))
        self.fr_replace_24.setFrameShape(QFrame.StyledPanel)
        self.fr_replace_24.setFrameShadow(QFrame.Raised)
        self.label_125 = QLabel(self.fr_replace_24)
        self.label_125.setObjectName(u"label_125")
        self.label_125.setGeometry(QRect(10, 5, 31, 21))
        self.label_126 = QLabel(self.fr_replace_24)
        self.label_126.setObjectName(u"label_126")
        self.label_126.setGeometry(QRect(180, 5, 51, 21))
        self.label_127 = QLabel(self.fr_replace_24)
        self.label_127.setObjectName(u"label_127")
        self.label_127.setGeometry(QRect(90, 5, 31, 21))
        self.input_year_12 = QSpinBox(self.fr_replace_24)
        self.input_year_12.setObjectName(u"input_year_12")
        self.input_year_12.setGeometry(QRect(40, 5, 51, 22))
        self.input_year_12.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_year_12.setMinimum(1900)
        self.input_year_12.setMaximum(3000)
        self.input_year_12.setValue(2000)
        self.input_month_12 = QSpinBox(self.fr_replace_24)
        self.input_month_12.setObjectName(u"input_month_12")
        self.input_month_12.setGeometry(QRect(110, 5, 51, 22))
        self.input_month_12.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.input_month_12.setMinimum(1)
        self.input_month_12.setMaximum(12)
        self.input_month_12.setValue(1)
        self.label_128 = QLabel(self.fr_replace_24)
        self.label_128.setObjectName(u"label_128")
        self.label_128.setGeometry(QRect(160, 5, 21, 21))
        self.label_129 = QLabel(self.fr_replace_24)
        self.label_129.setObjectName(u"label_129")
        self.label_129.setGeometry(QRect(280, 5, 31, 21))
        self.label_130 = QLabel(self.fr_replace_24)
        self.label_130.setObjectName(u"label_130")
        self.label_130.setGeometry(QRect(350, 5, 31, 21))
        self.output_month_12 = QSpinBox(self.fr_replace_24)
        self.output_month_12.setObjectName(u"output_month_12")
        self.output_month_12.setGeometry(QRect(300, 5, 51, 22))
        self.output_month_12.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_month_12.setMinimum(1)
        self.output_month_12.setMaximum(12)
        self.output_month_12.setValue(1)
        self.output_year_12 = QSpinBox(self.fr_replace_24)
        self.output_year_12.setObjectName(u"output_year_12")
        self.output_year_12.setGeometry(QRect(230, 5, 51, 22))
        self.output_year_12.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.output_year_12.setMinimum(1900)
        self.output_year_12.setMaximum(3000)
        self.output_year_12.setValue(2021)
        self.date_enable_12 = QCheckBox(self.fr_replace_24)
        self.date_enable_12.setObjectName(u"date_enable_12")
        self.date_enable_12.setGeometry(QRect(380, 5, 61, 19))
        self.date_enable_12.setChecked(True)
        self.enable_all_date = QPushButton(self.tab_4)
        self.enable_all_date.setObjectName(u"enable_all_date")
        self.enable_all_date.setGeometry(QRect(550, 170, 231, 51))
        self.enable_all_date.setStyleSheet(u"background-color: rgb(0, 170, 127);")
        self.label_131 = QLabel(self.tab_4)
        self.label_131.setObjectName(u"label_131")
        self.label_131.setGeometry(QRect(780, 240, 161, 21))
        self.replacedate_filter = QTextEdit(self.tab_4)
        self.replacedate_filter.setObjectName(u"replacedate_filter")
        self.replacedate_filter.setGeometry(QRect(780, 280, 151, 101))
        self.replacedate_filter.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tabWidget.addTab(self.tab_4, "")
        self.exec_all_btn = QPushButton(self.centralwidget)
        self.exec_all_btn.setObjectName(u"exec_all_btn")
        self.exec_all_btn.setGeometry(QRect(930, 740, 81, 41))
        water_mainwd.setCentralWidget(self.centralwidget)
        self.label_36.raise_()
        self.result_lbl.raise_()
        self.exec_btn.raise_()
        self.clear_output_btn.raise_()
        self.open_when_fin_btn.raise_()
        self.sel_input_lbl.raise_()
        self.sel_input_btn.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.sel_output_btn.raise_()
        self.sel_output_lbl.raise_()
        self.frame.raise_()
        self.exec_all_btn.raise_()
        self.menubar = QMenuBar(water_mainwd)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1031, 26))
        water_mainwd.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(water_mainwd)
        self.statusbar.setObjectName(u"statusbar")
        water_mainwd.setStatusBar(self.statusbar)

        self.retranslateUi(water_mainwd)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(water_mainwd)
    # setupUi

    def retranslateUi(self, water_mainwd):
        water_mainwd.setWindowTitle(QCoreApplication.translate("water_mainwd", u"\u6587\u6863\u6279\u91cf\u5904\u7406", None))
        self.exec_btn.setText(QCoreApplication.translate("water_mainwd", u"\u6267\u884c", None))
        self.clear_output_btn.setText(QCoreApplication.translate("water_mainwd", u"clear", None))
        self.open_when_fin_btn.setText("")
        self.label_36.setText(QCoreApplication.translate("water_mainwd", u"\u5b8c\u6210\u540e\n"
"\u6253\u5f00:", None))
        self.sel_input_lbl.setText("")
        self.sel_input_btn.setText(QCoreApplication.translate("water_mainwd", u"...", None))
        self.label_18.setText(QCoreApplication.translate("water_mainwd", u"\u8f93\u5165\u6587\u4ef6\u5939\u9009\u62e9:", None))
        self.label_19.setText("")
        self.sel_output_btn.setText(QCoreApplication.translate("water_mainwd", u"...", None))
        self.sel_output_lbl.setText("")
        self.label_21.setText(QCoreApplication.translate("water_mainwd", u"\u6587\u4ef6\u521b\u5efa\u65e5\u671f\u4fee\u6539\u4e3a: ", None))
        self.label_22.setText(QCoreApplication.translate("water_mainwd", u"\u81f3", None))
        self.label_23.setText(QCoreApplication.translate("water_mainwd", u"\u7684\u968f\u673a\u65f6\u95f4\u6bb5", None))
        self.label_24.setText(QCoreApplication.translate("water_mainwd", u"\u6587\u4ef6\u4fee\u6539\u65e5\u671f\u4fee\u6539\u4e3a\u521b\u5efa\u65e5\u671f\u4e4b\u540e\u7684", None))
        self.label_26.setText(QCoreApplication.translate("water_mainwd", u"\u81f3", None))
        self.label_27.setText(QCoreApplication.translate("water_mainwd", u"\u5c0f\u65f6\u7684\u968f\u673a\u65f6\u6bb5", None))
        self.label_28.setText(QCoreApplication.translate("water_mainwd", u"\u6587\u4ef6\u8bbf\u95ee\u65e5\u671f\u4fee\u6539\u4e3a\u4fee\u6539\u65e5\u671f\u4e4b\u540e\u7684", None))
        self.label_29.setText(QCoreApplication.translate("water_mainwd", u"\u5c0f\u65f6\u7684\u968f\u673a\u65f6\u6bb5", None))
        self.label_30.setText(QCoreApplication.translate("water_mainwd", u"\u81f3", None))
        self.modattr_filter.setHtml(QCoreApplication.translate("water_mainwd", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label_31.setText(QCoreApplication.translate("water_mainwd", u"\u4e0d\u4fee\u6539\u7684\u6587\u4ef6\u7c7b\u578b\u5217\u8868", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QCoreApplication.translate("water_mainwd", u"\u6587\u4ef6\u65e5\u671f\u5c5e\u6027\u4fee\u6539", None))
        self.replace_input_lbl_1.setText("")
        self.label_32.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_33.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.replace_output_lbl_1.setText("")
        self.label_57.setText(QCoreApplication.translate("water_mainwd", u"(\u82e5\u66ff\u6362\u8f93\u5165\u9879\u4e3a\u6b63\u5219\u8868\u8fbe\u5f0f\uff0c\u5219\u66ff\u6362\u8f93\u51fa\u53ef\u7528\u201cX1\u201d\u8868\u793a\u7b2c\u4e00\u4e2a\u5339\u914d\u9879\uff0c\u4f7f\u7528python\u8868\u8fbe\u5f0f\u8ba1\u7b97\u540e\u66ff\u6362)", None))
        self.label_58.setText(QCoreApplication.translate("water_mainwd", u"\u4fee\u6539\u7684\u6587\u4ef6\u7c7b\u578b\u5217\u8868", None))
        self.replacefile_filter.setHtml(QCoreApplication.translate("water_mainwd", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">doc</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">docx</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">xls</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">xlsx</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ppt</p>\n"
"<p style=\" margin-top:0p"
                        "x; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">pptx</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">txt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">csv</p></body></html>", None))
        self.replace_input_lbl_2.setText("")
        self.label_34.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_35.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.replace_output_lbl_2.setText("")
        self.replace_input_lbl_3.setText("")
        self.label_37.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_38.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.replace_output_lbl_3.setText("")
        self.replace_input_lbl_4.setText("")
        self.label_39.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_40.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.replace_output_lbl_4.setText("")
        self.replace_input_lbl_5.setText("")
        self.label_41.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_42.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.replace_output_lbl_5.setText("")
        self.replace_input_lbl_6.setText("")
        self.label_43.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_44.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.replace_output_lbl_6.setText("")
        self.replace_input_lbl_7.setText("")
        self.label_45.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_46.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.replace_output_lbl_7.setText("")
        self.replace_input_lbl_8.setText("")
        self.label_47.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_48.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.replace_output_lbl_8.setText("")
        self.replace_input_lbl_9.setText("")
        self.label_49.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_50.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.replace_output_lbl_9.setText("")
        self.replace_input_lbl_10.setText("")
        self.label_51.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_52.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.replace_output_lbl_10.setText("")
        self.replace_input_lbl_11.setText("")
        self.label_53.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_54.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.replace_output_lbl_11.setText("")
        self.replace_input_lbl_12.setText("")
        self.label_55.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_56.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.replace_output_lbl_12.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("water_mainwd", u"\u6587\u4ef6\u5185\u5bb9\u4fee\u6539\u66ff\u6362", None))
        self.rootshow_filter.setHtml(QCoreApplication.translate("water_mainwd", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">~\\$.*\\.xls[x]?</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">~\\$.*\\.doc[x]?</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">~\\$.*\\.ppt[x]?</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label_20.setText(QCoreApplication.translate("water_mainwd", u"\u4e0d\u751f\u6210\u76ee\u5f55\u7684\u6587\u4ef6\u7c7b\u578b\u5217\u8868", None))
        self.radioButton_toprint.setText(QCoreApplication.translate("water_mainwd", u"\u4ec5\u6253\u5370", None))
        self.radioButton_toword.setText(QCoreApplication.translate("water_mainwd", u"\u8f93\u51fa\u4e3aword\u6587\u6863", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("water_mainwd", u"\u8f93\u51fa\u76ee\u5f55\u7ed3\u6784", None))
        self.label_59.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_60.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.label_61.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_62.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.label_63.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_64.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.date_enable_1.setText(QCoreApplication.translate("water_mainwd", u"\u542f\u7528", None))
        self.year_input_to_all.setText(QCoreApplication.translate("water_mainwd", u"\u5c06\u7b2c\u4e00\u884c\u7684\u201c\u5e74\u201d\u8f93\u5165\n"
"\u5e94\u7528\u4e8e\u6240\u7528\u884c", None))
        self.month_asc_input.setText(QCoreApplication.translate("water_mainwd", u"\u201c\u6708\u201d\u9012\u589e\u586b\u5145", None))
        self.label_65.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_66.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.label_67.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_68.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.label_69.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_70.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.date_enable_2.setText(QCoreApplication.translate("water_mainwd", u"\u542f\u7528", None))
        self.label_71.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_72.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.label_73.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_74.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.label_75.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_76.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.date_enable_3.setText(QCoreApplication.translate("water_mainwd", u"\u542f\u7528", None))
        self.label_77.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_78.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.label_79.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_80.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.label_81.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_82.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.date_enable_4.setText(QCoreApplication.translate("water_mainwd", u"\u542f\u7528", None))
        self.label_83.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_84.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.label_85.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_86.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.label_87.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_88.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.date_enable_5.setText(QCoreApplication.translate("water_mainwd", u"\u542f\u7528", None))
        self.label_89.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_90.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.label_91.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_92.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.label_93.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_94.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.date_enable_6.setText(QCoreApplication.translate("water_mainwd", u"\u542f\u7528", None))
        self.label_95.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_96.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.label_97.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_98.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.label_99.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_100.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.date_enable_7.setText(QCoreApplication.translate("water_mainwd", u"\u542f\u7528", None))
        self.label_101.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_102.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.label_103.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_104.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.label_105.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_106.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.date_enable_8.setText(QCoreApplication.translate("water_mainwd", u"\u542f\u7528", None))
        self.label_107.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_108.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.label_109.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_110.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.label_111.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_112.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.date_enable_9.setText(QCoreApplication.translate("water_mainwd", u"\u542f\u7528", None))
        self.label_113.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_114.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.label_115.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_116.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.label_117.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_118.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.date_enable_10.setText(QCoreApplication.translate("water_mainwd", u"\u542f\u7528", None))
        self.label_119.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_120.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.label_121.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_122.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.label_123.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_124.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.date_enable_11.setText(QCoreApplication.translate("water_mainwd", u"\u542f\u7528", None))
        self.label_125.setText(QCoreApplication.translate("water_mainwd", u"\u5c06", None))
        self.label_126.setText(QCoreApplication.translate("water_mainwd", u"\u66ff\u6362\u4e3a", None))
        self.label_127.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_128.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.label_129.setText(QCoreApplication.translate("water_mainwd", u"\u5e74", None))
        self.label_130.setText(QCoreApplication.translate("water_mainwd", u"\u6708", None))
        self.date_enable_12.setText(QCoreApplication.translate("water_mainwd", u"\u542f\u7528", None))
        self.enable_all_date.setText(QCoreApplication.translate("water_mainwd", u"\u542f\u7528/\u53d6\u6d88\u6240\u6709\u884c", None))
        self.label_131.setText(QCoreApplication.translate("water_mainwd", u"\u4fee\u6539\u7684\u6587\u4ef6\u7c7b\u578b\u5217\u8868", None))
        self.replacedate_filter.setHtml(QCoreApplication.translate("water_mainwd", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">doc</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">docx</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">xls</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">xlsx</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ppt</p>\n"
"<p style=\" margin-top:0p"
                        "x; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">pptx</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">txt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">csv</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">log</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("water_mainwd", u"\u6587\u4ef6\u5185\u5bb9\u65e5\u671f\u66ff\u6362", None))
        self.exec_all_btn.setText(QCoreApplication.translate("water_mainwd", u"\u4e00\u952e\u6267\u884c\n"
"\u6240\u6709\u529f\u80fd", None))
    # retranslateUi

